// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekajksslaqpvafbqlcel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrYWprc3NsYXFwdmFmYnFsY2VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTU4NTIsImV4cCI6MjA2NzQ5MTg1Mn0.zisJ6ZF0gXQz2Our7y0sWMLCbKtnb9TKwMSVhyEnnPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});